# Generated by Django 5.0.6 on 2024-07-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_producttag_delete_image_remove_productshort_tags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
